### ISSUE TITLE
eth-provider fails to fallback if frame is not available

### ISSUE THREAD

**Issue by bumi** [floating/eth-provider#26]
It seems to me that eth-provider fails to fallback to the next target. 

I am trying to use eth-provider connected to frame and if frame is not available/running it should fallback to infura. 

The call to connect to frame fails with an `SyntaxError: Unexpected end of JSON input` error and thus the provider does not try to do the call through the next target. 

my code:
```js
const Web3 = require('web3');
const provider = require('eth-provider');

web3 = new Web3(provider('frame', 'infuraRinkeby'));
web3.eth.getBlockNumber().then(console.log)
```

which will result in:
```
(node:24771) UnhandledPromiseRejectionWarning: #<Object>
(node:24771) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

The error seems to happen in: https://github.com/floating/eth-provider/blob/master/connections/http.js#L103
A `console.log` in the catch block gives:
```
SyntaxError: Unexpected end of JSON input
```

Do you have an idea? If I understand the readme correct it should automatically fall back to infura in my code above, shouldn't it?

**Comment by bumi** [comment]
damn, sorry... I was holding it wrong...

should obviously be `provider(['frame', 'infuraRinkeby'])` with parameters passed as an array. 

sorry, for the spam and yay for rubber duck debugging :D

**Comment by floating** [comment]
No worries! I greatly appreciate anyone taking the time to open an issue when it seems like something isn't working correctly. I'm glad it was sorted out. 

Passing `targets` as standalone arguments is a bit cleaner but I think an array makes sense here because in the future the setup step will have a `settings` object that can be passed in to customize behavior. Both arguments (`targets` and `settings`) will stay optional so clearly containing each will make the interface less complex.

**Comment by bumi** [comment]
yeah, it totally makes sense like this. 
thanks!
